### ISSUE TITLE
models 现存的两个问题

### ISSUE THREAD

**Issue by ttys026** [umijs/plugin-model#1]
1. 在 umi 中 export 使用 `@tmp` 变量，在这个 example 中，发现配置 tsconfig 里的 alias 也不能解决编辑器的寻址。 因此 js 可以执行，但是 ts 类型带不过来。
![image](https://user-images.githubusercontent.com/19804057/69437752-d6435a00-0d7e-11ea-87c6-c4315f0fa40f.png)

2. 内网 Bigfish 锁的 umi 版本不会去写临时文件下的 `umiExports.d.ts` 文件，因此 model plugin 可以直接调 writeTmp 去写类型。
![image](https://user-images.githubusercontent.com/19804057/69438282-b6f8fc80-0d7f-11ea-897e-54013a4bcc2a.png)
13天前这次更新，把类型自动带上了。但是 model plugin 里有一个所有 Models 的类型希望导出给用户：
`export type Models<T extends keyof typeof models> = Model<T>[T]`

如果直接调 addUmiExports api，会在 js 文件里 export 类型，导致报错。使用 writeTmpFile 的方法，又因为 .d.ts 文件会被复写，导致没法 export 类型出来了

@sorrycc 云谦老师帮忙看一下这两个问题🙏

**Comment by sorrycc** [comment]
第一个问题在 #2 里修了，tsconfig.json 的路径问题；第二个问题在 https://github.com/umijs/umi/pull/3698 解决，umiExports 用 ts 文件。

**Comment by sorrycc** [comment]
+ umi@2.12.3
