### ISSUE TITLE
配套的 vscode 插件

### ISSUE THREAD

**Issue by sorrycc** [umijs/plugin-model#5]
两个功能，

1. 输入 useModel 时自动提示可选的 namespace
2. 点击 `useModel('todos')` 的 todos 时，跳转到 todos

vscode 插件名如果可以，直接用 `@umijs/plugin-model`。

**Comment by sorrycc** [comment]
@DiamondYuan 看下有没有兴趣。

**Comment by ttys026** [comment]
> 输入 useModel 时自动提示可选的 namespace。

这个通过 ts 自动推导已经能实现了

> 点击 useModel('todos') 的 todos 时，跳转到 todos

实现了一个版本，可以实现点击 namespace 跳转。
<img width="540" alt="model-plugin" src="https://user-images.githubusercontent.com/19804057/69802463-9cf26a80-1214-11ea-8f4a-35b39afd4d28.png">
https://marketplace.visualstudio.com/items?itemName=litiany4.umijs-plugin-model&ssr=false#overview

**Comment by sorrycc** [comment]
vscode 插件我试了下没有效果，源码也传到 umijs 下吧，可以叫 plugin-model-vscode。

**Comment by ttys026** [comment]
fixed, code in https://github.com/umijs/plugin-model-vscode
